### ISSUE TITLE
can't compile on ubuntu 16.06

### ISSUE THREAD

**Issue by iambetmen** [uwm-utility/core#1]
can't compile on ubuntu 16.06
i installing clang and libclang v3.8
============================
error messages

CXX src/unxt.cpp build/unxt.o
In file included from src/unxt.cpp:24:
In file included from src/wm/extra.hpp:30:
src/wm/tools.hpp:196:5: error: no matching function for call to 'xcb_change_window_attributes'
    xcb_change_window_attributes(&c, w, XCB_CW_OVERRIDE_REDIRECT, &val);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/xcb/xproto.h:5622:1: note: candidate function not viable: no known conversion from 'int *' to
      'const uint32_t *' (aka 'const unsigned int *') for 4th argument
xcb_change_window_attributes (xcb_connection_t *c  /**< */,
^
1 error generated.
Makefile:29: recipe for target 'build/unxt.o' failed
make: *** [build/unxt.o] Error 1

**Comment by thelostt** [comment]
Thanks!
